dist: xenial

sudo: false

language: python

matrix:
  include:
    - python: 3.7

cache:
  - pip

script:
  - echo 'OK'

deploy:
  - provider: pypi
    user: alevkin
    password:
      secure: "T+So+wwtDEIPZB4UAr2MH1ZZqlzTbYoUk315qWG6xbMZ3UZ3dPHbRbxT6Gsl2qvWQ9ZEnDZMLweEKBgN1zbSIHWVAMCLn4Kp7+Y6DVH5/E917T0dsZUeY+5dWPSmWsnd6xQTlQfhEOpLCxOjbLANSlpQTRaCPnEWd8CSwT7h1JqvB0kYNt8pVGsQWTNhVb8MUEnn6jZxL8SRowYbb2zlbFiwUqR6PJCu9UuAdV+tg3o7Gl68jL9lGAr8WIVh8gIZd6rn6MIg2+cS9RWALAjM3ehx4IBNv+9twIICJ0nrq6cn0HJHHBJ4llKXhABzim72QNS7dy8njGzk0/UyJedOGS888HaWnfNkb4Un6wbbH4R/mm5cce72DVGfhW3s1bx0dX+M6c4PW7uDpwCJsSl4hT27vZsU2NMNhVV25gesW8gucSZcpLYx9d6neA8Xx7/i0Aju0+5312NLTHj9UoL8l6PR6+hAeDg6ZBfuKjw0yuk3nEclk9N4AaQnUQepHG5FV8kiWc7DFrO+cLdzX+LDWqKvwObMN34NoYt7yqezWPcP4QXEsR+jynfPWoZWQ5wrwydBztxHEqGU7Y8zepvkjcnZaKLah3tM4nJKTyXndfwcovYiZ/wBaZIzdfZe8Wt17ZQNexsU7ef3cxF7IitBWSnp18v8H5k3/7ELLDSxzKg="
    distributions: sdist bdist_wheel
    on:
      tags: true
