language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7
    - os: osx
      osx_image: xcode11
      language: shell

sudo: false

cache:
  - pip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi

script:
  - make virtualenv
  - make dist

deploy:
  - provider: pypi
    user: alevkin
    password:
      secure: "XS3KiJA4iA9ctQbc+jBFAocg1xphTOLloFAcOmXp4fStXvZbnWQ0SynsJ+zrQ7/6I3lXxfiJMC3Rqew5BIliIRmUAoj4zXuWUqiU81OSimKHp8eItJwXcS7oOHuYxn2V5OxgbwhwMsVUXw9qhCzRDNLZj18kUkFZo1nks0XHebliC2ma6FKgxThFyPr5fqUwnnNpbZZgr1y51UeOAyCFvfR9ikE0sf82jwf3OOWpNXt0GtdE+atiA9Eql4SrQZKxJdBXxsvugB2/oLZO21buWy/DVfc9OWzcrCTsh6NxTM6N3ajsbzvB7eRtJjwIf6o3Prb+40sa1QUTdKoWy9+5PiFpj+2IuAoSmJH95Ms2itjk8Hv04SkJvnQyb1MVGuNj/QLp+y8gZK5laM6CfXO3v+IGuYIMrnbwSG//FuGTdFoPJGbCWiHICHpvJogzwbVQwJ9g5ot8Tl97JURHDDdkjNUvXfcjet9qdfJ5iIn/o+zqEnkjLelhdLW/s/rfIytvESppTb03SUQDX3XXk405ftrwzNczxfvtoxmYvfYYB5waBKmqfjfoT3m/oQ2jIs8FTmb7VU/zoc7RHruBQJTSGsfjDXSqsOxu+8YsA9HA9QaCrCT61wsqloCBR3HFvIuaudMLws3P6mg+AaMNsBzyLeA/bd4X1+pzLvZiQ1DwDv4="
    distributions: sdist bdist_wheel
    on:
      tags: true
