dist: xenial

sudo: false

language: python

matrix:
  include:
    - python: 3.7

cache:
  - pip

script:
  - echo 'OK'

deploy:
  - provider: pypi
    user: alevkin
    password:
      secure: fKKqjlDLQpm0s+DbzPRo6/toresBOtW3OGIcx1Mmj6iG/Ux7hZGERMXzk1ZgJBqlAVbzqmjP5yXWZYHbqlsxVhblJ4MJyasYGELbFcHddLcHU+/ZxiQo8bTcHPcUwMPngZh/Ssyeyv0oEKpjnmLhbY980RIWvAGlAB8Q09wKSUUgmhkkFXiwmODAOA4X4BALmTeyu5jYDZy0biGe7T7Imb41iHsyPllMcKhpDMvdMREZFC2N9wmEKz0gpAgrraXhTh+pHJkB/GOwrgRlIsWoQyIvROIPEIakeru+mVTlRF2ldjmbfAQdjn793GtYtVKaxApBTSLV/sVenRHQENJmBp84jMSphzsnfbHqGdO2f5mYOS7WgNJ1N15YXG9kWtobr+XjlMYB4dw4+ENA3uejUivz7K8NbCu61hKeNQwc5Vl193Jd1P5Gv4ZUyFxO0l+Y/HQeJMb5A2EEC/OLFiJCM8zRsB/jTN/JqltF462ufS2NkZouM8wXbWUcaXR9J1taVIHa82vAD9Z1SiMzMCKgoUDHATWv0GDPUdDIE5+ghRscFke1rK51Ow2Pr6fRlwpB4l7gZKMQyjT00wsfBN6dUmtXi2Kc8SchS97SkLa/Qw8jQU1AM6qsnRH3qOqWttu0bhBNMGuVboSm1d9+LgB6Bd58DZwHYoHEyb8EMNZcoAs=
    distributions: sdist bdist_wheel
    on:
      tags: true
